name: CI
on: 
  push:
    branches:
      - 'chameleoncloud/*'
  pull_request:

jobs:
  all-in-one:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install \
          tox \
          ansible
      - name: the included tests
        run: |
            ansible-playbook -i .github/ci/test-inventory tests/run.yml \
            -e action=deploy \
            -e scenario=all-in-one \
            -e kolla_install_type=source
