name: CI
on: [push, pull_request]

jobs:
  linters:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: pip install tox
      - name: Run Linters
        run: tox -e linters
  prechecks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: pip install tox
      - name: Run Prechecks
        run: tox -e prechecks
